version: '3.8'

volumes:
  db-data:

services:
  api:
    container_name: api
    build: .
    tty: true
    stdin_open: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - '.:/api'
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db: # service名は、ormconfig.tsのhostの値と同じにする
    container_name: db
    image: mysql:5.7.37
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
